// docs/components/gateway/discord-voice.md's "In Progress: Turn-Taking
// Model" — the contract between Gateway (Go, workflows/cmd/gateway) and the
// same vad-sidecar process that already serves Silero VAD (vad-sidecar/),
// extended to also serve LiveKit's turn-detector v1-mini (an audio-native
// end-of-turn model, self-hosted, CPU-only ONNX). Colocated as a SECOND
// gRPC service on the existing sidecar rather than a new container/pod —
// same "one same-pod process, no new resource footprint" reasoning that
// already justified colocating Silero there.
//
// Stateless-over-the-wire, unlike VAD: the model's own rolling window is
// fixed-size (EOT_MAX_SAMPLES, 19200 samples = 1.2s @ 16kHz) and the caller
// already owns the accumulated utterance buffer (speakerBuffer.pcm) — there
// is no per-speaker recurrent state to carry between calls the way Silero's
// RNN state is. Each call is a fresh, independent classification of
// whatever trailing window of audio the caller sends.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/eot_sidecar.proto

package eotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PredictRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw int16 PCM, little-endian, mono, 16kHz — packed as bytes (not
	// `repeated int32`) for the same per-element-overhead reason
	// vad_sidecar.proto's own ClassifyRequest packs its float32 fields.
	// Exactly EOT_MAX_SAMPLES (19200) samples — a caller with less than a
	// full window's worth of real audio zero-pads at the FRONT (oldest end),
	// matching the model's own rolling-buffer semantics (most recent audio
	// last) — verified against real audio this way, see the doc's own Notes
	// Log for the exact real-sample results this produced.
	Pcm           []byte `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_proto_eot_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eot_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_proto_eot_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *PredictRequest) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

type PredictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The model's raw end-of-turn probability — thresholding (a real,
	// per-language calibrated default, not invented here — see
	// voice_eot.go's own comment) is the Go client's job, not this
	// service's; this stays a pure, uninterpreted score.
	Probability   float32 `protobuf:"fixed32,1,opt,name=probability,proto3" json:"probability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_proto_eot_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_eot_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_proto_eot_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *PredictResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

var File_proto_eot_sidecar_proto protoreflect.FileDescriptor

const file_proto_eot_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x17proto/eot_sidecar.proto\x12\n" +
	"eotsidecar\"\"\n" +
	"\x0ePredictRequest\x12\x10\n" +
	"\x03pcm\x18\x01 \x01(\fR\x03pcm\"3\n" +
	"\x0fPredictResponse\x12 \n" +
	"\vprobability\x18\x01 \x01(\x02R\vprobability2I\n" +
	"\x03EOT\x12B\n" +
	"\aPredict\x12\x1a.eotsidecar.PredictRequest\x1a\x1b.eotsidecar.PredictResponseB(Z&agent-harness/workflows/internal/eotpbb\x06proto3"

var (
	file_proto_eot_sidecar_proto_rawDescOnce sync.Once
	file_proto_eot_sidecar_proto_rawDescData []byte
)

func file_proto_eot_sidecar_proto_rawDescGZIP() []byte {
	file_proto_eot_sidecar_proto_rawDescOnce.Do(func() {
		file_proto_eot_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_eot_sidecar_proto_rawDesc), len(file_proto_eot_sidecar_proto_rawDesc)))
	})
	return file_proto_eot_sidecar_proto_rawDescData
}

var file_proto_eot_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_eot_sidecar_proto_goTypes = []any{
	(*PredictRequest)(nil),  // 0: eotsidecar.PredictRequest
	(*PredictResponse)(nil), // 1: eotsidecar.PredictResponse
}
var file_proto_eot_sidecar_proto_depIdxs = []int32{
	0, // 0: eotsidecar.EOT.Predict:input_type -> eotsidecar.PredictRequest
	1, // 1: eotsidecar.EOT.Predict:output_type -> eotsidecar.PredictResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_eot_sidecar_proto_init() }
func file_proto_eot_sidecar_proto_init() {
	if File_proto_eot_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_eot_sidecar_proto_rawDesc), len(file_proto_eot_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_eot_sidecar_proto_goTypes,
		DependencyIndexes: file_proto_eot_sidecar_proto_depIdxs,
		MessageInfos:      file_proto_eot_sidecar_proto_msgTypes,
	}.Build()
	File_proto_eot_sidecar_proto = out.File
	file_proto_eot_sidecar_proto_goTypes = nil
	file_proto_eot_sidecar_proto_depIdxs = nil
}
