// docs/components/gateway/discord-voice.md's "In Progress: Turn-Taking
// Model" — the contract between Gateway (Go, workflows/cmd/gateway) and the
// same vad-sidecar process that already serves Silero VAD (vad-sidecar/),
// extended to also serve LiveKit's turn-detector v1-mini (an audio-native
// end-of-turn model, self-hosted, CPU-only ONNX). Colocated as a SECOND
// gRPC service on the existing sidecar rather than a new container/pod —
// same "one same-pod process, no new resource footprint" reasoning that
// already justified colocating Silero there.
//
// Stateless-over-the-wire, unlike VAD: the model's own rolling window is
// fixed-size (EOT_MAX_SAMPLES, 19200 samples = 1.2s @ 16kHz) and the caller
// already owns the accumulated utterance buffer (speakerBuffer.pcm) — there
// is no per-speaker recurrent state to carry between calls the way Silero's
// RNN state is. Each call is a fresh, independent classification of
// whatever trailing window of audio the caller sends.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: proto/eot_sidecar.proto

package eotpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EOT_Predict_FullMethodName = "/eotsidecar.EOT/Predict"
)

// EOTClient is the client API for EOT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EOTClient interface {
	// Predict scores one utterance-so-far window and returns the model's
	// probability that the speaker has finished their turn.
	Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error)
}

type eOTClient struct {
	cc grpc.ClientConnInterface
}

func NewEOTClient(cc grpc.ClientConnInterface) EOTClient {
	return &eOTClient{cc}
}

func (c *eOTClient) Predict(ctx context.Context, in *PredictRequest, opts ...grpc.CallOption) (*PredictResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PredictResponse)
	err := c.cc.Invoke(ctx, EOT_Predict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EOTServer is the server API for EOT service.
// All implementations must embed UnimplementedEOTServer
// for forward compatibility.
type EOTServer interface {
	// Predict scores one utterance-so-far window and returns the model's
	// probability that the speaker has finished their turn.
	Predict(context.Context, *PredictRequest) (*PredictResponse, error)
	mustEmbedUnimplementedEOTServer()
}

// UnimplementedEOTServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEOTServer struct{}

func (UnimplementedEOTServer) Predict(context.Context, *PredictRequest) (*PredictResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Predict not implemented")
}
func (UnimplementedEOTServer) mustEmbedUnimplementedEOTServer() {}
func (UnimplementedEOTServer) testEmbeddedByValue()             {}

// UnsafeEOTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EOTServer will
// result in compilation errors.
type UnsafeEOTServer interface {
	mustEmbedUnimplementedEOTServer()
}

func RegisterEOTServer(s grpc.ServiceRegistrar, srv EOTServer) {
	// If the following call panics, it indicates UnimplementedEOTServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EOT_ServiceDesc, srv)
}

func _EOT_Predict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PredictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EOTServer).Predict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EOT_Predict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EOTServer).Predict(ctx, req.(*PredictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EOT_ServiceDesc is the grpc.ServiceDesc for EOT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EOT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eotsidecar.EOT",
	HandlerType: (*EOTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Predict",
			Handler:    _EOT_Predict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/eot_sidecar.proto",
}
