# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: eot_sidecar.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'eot_sidecar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65ot_sidecar.proto\x12\neotsidecar\"\x1d\n\x0ePredictRequest\x12\x0b\n\x03pcm\x18\x01 \x01(\x0c\"&\n\x0fPredictResponse\x12\x13\n\x0bprobability\x18\x01 \x01(\x02\x32I\n\x03\x45OT\x12\x42\n\x07Predict\x12\x1a.eotsidecar.PredictRequest\x1a\x1b.eotsidecar.PredictResponseB(Z&agent-harness/workflows/internal/eotpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'eot_sidecar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&agent-harness/workflows/internal/eotpb'
  _globals['_PREDICTREQUEST']._serialized_start=33
  _globals['_PREDICTREQUEST']._serialized_end=62
  _globals['_PREDICTRESPONSE']._serialized_start=64
  _globals['_PREDICTRESPONSE']._serialized_end=102
  _globals['_EOT']._serialized_start=104
  _globals['_EOT']._serialized_end=177
# @@protoc_insertion_point(module_scope)
