// docs/components/gateway/discord-voice.md's "Resolved: Silero VAD" — the
// contract between Gateway (Go, workflows/cmd/gateway) and the VAD sidecar
// (Python, vad-sidecar/). Stateless-over-the-wire by design: Silero's real
// ONNX export takes state as an explicit input/output, so the caller
// (Gateway) owns per-speaker state and passes it with every call — this
// service holds no per-connection or per-speaker state at all.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: vad_sidecar.proto

package vadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw float32, little-endian, exactly 512 samples (Silero's fixed
	// window size at 16kHz) — packed as bytes, not `repeated float`, to
	// avoid per-element protobuf varint/tag overhead on a hot path called
	// ~50x/sec per active speaker.
	Frame []byte `protobuf:"bytes,1,opt,name=frame,proto3" json:"frame,omitempty"`
	// Raw float32, little-endian, exactly 256 values (Silero's [2,1,128]
	// recurrent state tensor, flattened).
	State []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Raw float32, little-endian, exactly 64 values (Silero's rolling
	// audio context, prepended to each new frame).
	Context       []byte `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_vad_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vad_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_vad_sidecar_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *ClassifyRequest) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ClassifyRequest) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probability   float32                `protobuf:"fixed32,1,opt,name=probability,proto3" json:"probability,omitempty"`
	State         []byte                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`     // updated state — feed into the next Classify call
	Context       []byte                 `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"` // updated context — feed into the next Classify call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_vad_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vad_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_vad_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *ClassifyResponse) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ClassifyResponse) GetContext() []byte {
	if x != nil {
		return x.Context
	}
	return nil
}

var File_vad_sidecar_proto protoreflect.FileDescriptor

const file_vad_sidecar_proto_rawDesc = "" +
	"\n" +
	"\x11vad_sidecar.proto\x12\n" +
	"vadsidecar\"W\n" +
	"\x0fClassifyRequest\x12\x14\n" +
	"\x05frame\x18\x01 \x01(\fR\x05frame\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext\"d\n" +
	"\x10ClassifyResponse\x12 \n" +
	"\vprobability\x18\x01 \x01(\x02R\vprobability\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\x12\x18\n" +
	"\acontext\x18\x03 \x01(\fR\acontext2L\n" +
	"\x03VAD\x12E\n" +
	"\bClassify\x12\x1b.vadsidecar.ClassifyRequest\x1a\x1c.vadsidecar.ClassifyResponseB(Z&agent-harness/workflows/internal/vadpbb\x06proto3"

var (
	file_vad_sidecar_proto_rawDescOnce sync.Once
	file_vad_sidecar_proto_rawDescData []byte
)

func file_vad_sidecar_proto_rawDescGZIP() []byte {
	file_vad_sidecar_proto_rawDescOnce.Do(func() {
		file_vad_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vad_sidecar_proto_rawDesc), len(file_vad_sidecar_proto_rawDesc)))
	})
	return file_vad_sidecar_proto_rawDescData
}

var file_vad_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vad_sidecar_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: vadsidecar.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: vadsidecar.ClassifyResponse
}
var file_vad_sidecar_proto_depIdxs = []int32{
	0, // 0: vadsidecar.VAD.Classify:input_type -> vadsidecar.ClassifyRequest
	1, // 1: vadsidecar.VAD.Classify:output_type -> vadsidecar.ClassifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vad_sidecar_proto_init() }
func file_vad_sidecar_proto_init() {
	if File_vad_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vad_sidecar_proto_rawDesc), len(file_vad_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vad_sidecar_proto_goTypes,
		DependencyIndexes: file_vad_sidecar_proto_depIdxs,
		MessageInfos:      file_vad_sidecar_proto_msgTypes,
	}.Build()
	File_vad_sidecar_proto = out.File
	file_vad_sidecar_proto_goTypes = nil
	file_vad_sidecar_proto_depIdxs = nil
}
