// docs/components/gateway/discord-voice.md's "Resolved: Silero VAD" — the
// contract between Gateway (Go, workflows/cmd/gateway) and the VAD sidecar
// (Python, vad-sidecar/). Stateless-over-the-wire by design: Silero's real
// ONNX export takes state as an explicit input/output, so the caller
// (Gateway) owns per-speaker state and passes it with every call — this
// service holds no per-connection or per-speaker state at all.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: vad_sidecar.proto

package vadpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VAD_Classify_FullMethodName = "/vadsidecar.VAD/Classify"
)

// VADClient is the client API for VAD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VADClient interface {
	// Classify scores one 512-sample window at 16kHz (32ms) — Silero's
	// fixed window size, not negotiable.
	Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error)
}

type vADClient struct {
	cc grpc.ClientConnInterface
}

func NewVADClient(cc grpc.ClientConnInterface) VADClient {
	return &vADClient{cc}
}

func (c *vADClient) Classify(ctx context.Context, in *ClassifyRequest, opts ...grpc.CallOption) (*ClassifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyResponse)
	err := c.cc.Invoke(ctx, VAD_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VADServer is the server API for VAD service.
// All implementations must embed UnimplementedVADServer
// for forward compatibility.
type VADServer interface {
	// Classify scores one 512-sample window at 16kHz (32ms) — Silero's
	// fixed window size, not negotiable.
	Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error)
	mustEmbedUnimplementedVADServer()
}

// UnimplementedVADServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVADServer struct{}

func (UnimplementedVADServer) Classify(context.Context, *ClassifyRequest) (*ClassifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedVADServer) mustEmbedUnimplementedVADServer() {}
func (UnimplementedVADServer) testEmbeddedByValue()             {}

// UnsafeVADServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VADServer will
// result in compilation errors.
type UnsafeVADServer interface {
	mustEmbedUnimplementedVADServer()
}

func RegisterVADServer(s grpc.ServiceRegistrar, srv VADServer) {
	// If the following call panics, it indicates UnimplementedVADServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VAD_ServiceDesc, srv)
}

func _VAD_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VADServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VAD_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VADServer).Classify(ctx, req.(*ClassifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VAD_ServiceDesc is the grpc.ServiceDesc for VAD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VAD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vadsidecar.VAD",
	HandlerType: (*VADServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _VAD_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vad_sidecar.proto",
}
