apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent-harness-shared.fullname" . }}
  labels:
    {{- include "agent-harness-shared.labels" . | nindent 4 }}
automountServiceAccountToken: false
